### ISSUE TITLE
64bits(double, int64) data type error

### ISSUE THREAD

**Issue by OpusK** [eProsima/micro-RTPS#5]
Hi,

I am doing a topic test with microRTPS and ROS2. Most topics are communicating without problems. (using ros2 topic echo)
However, there is a problem with double and int64 types. That is, the problem occurs only in 8 bytes.

For example, if I send a value of 1234567891011121314 as an int64 type, ros2 ehco a value of -5561329117506306048.
Even the last 4 digits sometimes change!

[Here](https://github.com/ROBOTIS-GIT/OpenCR/tree/feature-ros2-micrortps/arduino/opencr_arduino/opencr/libraries/ROS2/examples) are some examples using for test.

I am currently using microRTPS in the 32bit ARM core. Do you have any idea about these issues?

**Comment by lemunozm** [comment]
Hi @OpusK, thank you for your report.

There is a problem with the padding when a type of 8 bytes is serialized at first element of a message. We will fix it in the future release.

In the meantime, the problem can be easily avoied adding a padding in your generated topic serialization file, inside of `size_of_TYPENAME_topic` function. This change must be done ONLY in case the FIRST serialized element size was 8 bytes. 

As an example, the `size_of_topic` function of your `Int64.hpp` file would be:
```c
  virtual uint32_t size_of_topic(const Int64* topic)
  {
      (void)(topic);
      uint32_t size = 0;

      size += 8 + get_alignment(size, 8);

      return size + 4;
  }
```

**Comment by lemunozm** [comment]
Hi @OpusK, thank you for your report.

There is a problem with the padding when a type of 8 bytes is serialized. We will fix it in the future release. The problem is because of different serialization alignment between the CDR version used by ROS2 (FastRTPS) and MicroRTPS.

Sorry by the inconvenience. For now, the "solution" may be to serialize the 8-byte type as an array of 8 bytes. If all machines that will use the topic have the same endianness, it works (tipically little endianness).

**Comment by OpusK** [comment]
Can you tell me where to modify CDR from microRTPS, rmw, or agent?
While I wait for the release, I want to modify it myself and test it.

**Comment by lemunozm** [comment]
Hi @OpusK. The change is not trivial. The solution consist in changing several parts of how the topics are serialized and deserialized respect to the rest of the XRCE message.

The new release will be available soon with these changes. We hope to upload it on Github this Friday. I will let you know when it is ready.

**Comment by lemunozm** [comment]
HI @OpusK. Sorry for the delay. 

We have released the new version of the client API fixing this error and adding several new features. You can download it in the repo `https://github.com/eProsima/micro-RTPS-client` under branch `release/1.0.0beta2`. This client is only compatible with the agent at the same branch name.

These versions are under testing. When we finish it, we will up to master. This client version has the API that will contain the master branch.

**Comment by OpusK** [comment]
Oh, finally! Thank you @lemunozm . :) I will try my code with this soon and let you know.

**Comment by OpusK** [comment]
My answer is late!
This is working very well :) Thanks.
